- name: git clone
  sudo: False
  git: repo=https://github.com/tank-bohr/enode.git dest=~{{ user }}/erlang-enode

- name: Set hostname for erlang longnmaes
  hostname: name=erlang-enode-ubuntu.local

- name: Add rabbitmq repo
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: Add apt key
  apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

- name: Install rabbitmq
  apt: pkg=rabbitmq-server state=latest update_cache=yes

- name: packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - make
    - htop

- name: Get deps
  sudo: False
  command: ./rebar get-deps chdir=~{{ user }}/erlang-enode

- name: Fix eiconv rebar.config
  sudo: False
  lineinfile: backup=yes state=absent regexp=require_otp_vsn dest=~{{ user }}/erlang-enode/deps/eiconv/rebar.config

- name: Compile
  sudo: False
  command: ./rebar compile chdir=~{{ user }}/erlang-enode

- name: Put private key for dkim
  sudo: False
  copy: src=../apps/enode/priv/private-key.pem dest=~{{ user }}/erlang-enode/apps/enode/priv/private-key.pem
